site_name: Clip
theme:
  name: material
  icon:
    repo: fontawesome/brands/github

repo_name: erdnaxei/clip
repo_url: https://github.com/erdnaxeli/clip
edit_uri: edit/main/docs/

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

nav:
  - Clip: index.md
  - User guide:
    - Setup: user guide/setup.md
    - First steps: user guide/first_steps.md
    - Options:
      - Optional options: user guide/options/optional.md
      - Required options: user guide/options/required.md
      - Nillable options: user guide/options/nillable.md
      - Flags: user guide/options/flags.md
      - Option name: user guide/options/name.md
      - Option types: user guide/options/types.md
    - Arguments:
      - Required arguments: user guide/arguments/required.md
      - Optional arguments: user guide/arguments/optional.md
      - Nillable arguments: user guide/arguments/nillable.md
      - Argument types: user guide/arguments/types.md
      - Multiple arguments: user guide/arguments/multiple.md
    - Documentation: user guide/doc.md
