site_name: Clip
theme:
  name: material
  icon:
    repo: fontawesome/brands/github

repo_name: erdnaxei/clip
repo_url: https://github.com/erdnaxeli/clip
edit_uri: edit/main/docs/

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - abbr
  - pymdownx.snippets
  - toc:
      permalink: true

nav:
  - Clip: index.md
  - Features: features.md
  - User guide:
    - Setup: user guide/setup.md
    - First steps: user guide/first_steps.md
    - Options:
      - Optional options: user guide/options/optional.md
      - Required options: user guide/options/required.md
      - Nilable options: user guide/options/nilable.md
      - Flags: user guide/options/flags.md
      - Option name: user guide/options/name.md
      - Option types: user guide/options/types.md
    - Arguments:
      - Required arguments: user guide/arguments/required.md
      - Optional arguments: user guide/arguments/optional.md
      - Nilable arguments: user guide/arguments/nilable.md
      - Argument types: user guide/arguments/types.md
      - Multiple arguments: user guide/arguments/multiple.md
    - Documentation: user guide/doc.md
    - Commands: user guide/commands.md
    - Help: user guide/help.md
    - Multiple values: user guide/arrays.md
    - Errors: user guide/errors.md
    - Non CLI applications: user guide/non_cli_app.md
  - Alternatives: alternatives.md
  - Get help — Help Clip: help.md
  - Contributing: contributing.md
  - Release notes: release-notes.md

extra_css:
  - css/custom.css
